/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeReviewRouteImport } from './routes/employee_.review'
import { Route as EmployeeGoalsRouteImport } from './routes/employee_.goals'
import { Route as EmployeeFeedbackRouteImport } from './routes/employee_.feedback'
import { Route as EmployeeCheckinsRouteImport } from './routes/employee_.checkins'
import { Route as EmployeeActivityRouteImport } from './routes/employee_.activity'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeReviewRoute = EmployeeReviewRouteImport.update({
  id: '/employee_/review',
  path: '/employee/review',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeGoalsRoute = EmployeeGoalsRouteImport.update({
  id: '/employee_/goals',
  path: '/employee/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeFeedbackRoute = EmployeeFeedbackRouteImport.update({
  id: '/employee_/feedback',
  path: '/employee/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeCheckinsRoute = EmployeeCheckinsRouteImport.update({
  id: '/employee_/checkins',
  path: '/employee/checkins',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeActivityRoute = EmployeeActivityRouteImport.update({
  id: '/employee_/activity',
  path: '/employee/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/employee': typeof EmployeeRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/employee/activity': typeof EmployeeActivityRoute
  '/employee/checkins': typeof EmployeeCheckinsRoute
  '/employee/feedback': typeof EmployeeFeedbackRoute
  '/employee/goals': typeof EmployeeGoalsRoute
  '/employee/review': typeof EmployeeReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/employee': typeof EmployeeRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/employee/activity': typeof EmployeeActivityRoute
  '/employee/checkins': typeof EmployeeCheckinsRoute
  '/employee/feedback': typeof EmployeeFeedbackRoute
  '/employee/goals': typeof EmployeeGoalsRoute
  '/employee/review': typeof EmployeeReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/employee': typeof EmployeeRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/employee_/activity': typeof EmployeeActivityRoute
  '/employee_/checkins': typeof EmployeeCheckinsRoute
  '/employee_/feedback': typeof EmployeeFeedbackRoute
  '/employee_/goals': typeof EmployeeGoalsRoute
  '/employee_/review': typeof EmployeeReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/employee'
    | '/login'
    | '/manager'
    | '/employee/activity'
    | '/employee/checkins'
    | '/employee/feedback'
    | '/employee/goals'
    | '/employee/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/employee'
    | '/login'
    | '/manager'
    | '/employee/activity'
    | '/employee/checkins'
    | '/employee/feedback'
    | '/employee/goals'
    | '/employee/review'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/employee'
    | '/login'
    | '/manager'
    | '/employee_/activity'
    | '/employee_/checkins'
    | '/employee_/feedback'
    | '/employee_/goals'
    | '/employee_/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EmployeeRoute: typeof EmployeeRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  EmployeeActivityRoute: typeof EmployeeActivityRoute
  EmployeeCheckinsRoute: typeof EmployeeCheckinsRoute
  EmployeeFeedbackRoute: typeof EmployeeFeedbackRoute
  EmployeeGoalsRoute: typeof EmployeeGoalsRoute
  EmployeeReviewRoute: typeof EmployeeReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee_/review': {
      id: '/employee_/review'
      path: '/employee/review'
      fullPath: '/employee/review'
      preLoaderRoute: typeof EmployeeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee_/goals': {
      id: '/employee_/goals'
      path: '/employee/goals'
      fullPath: '/employee/goals'
      preLoaderRoute: typeof EmployeeGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee_/feedback': {
      id: '/employee_/feedback'
      path: '/employee/feedback'
      fullPath: '/employee/feedback'
      preLoaderRoute: typeof EmployeeFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee_/checkins': {
      id: '/employee_/checkins'
      path: '/employee/checkins'
      fullPath: '/employee/checkins'
      preLoaderRoute: typeof EmployeeCheckinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee_/activity': {
      id: '/employee_/activity'
      path: '/employee/activity'
      fullPath: '/employee/activity'
      preLoaderRoute: typeof EmployeeActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EmployeeRoute: EmployeeRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  EmployeeActivityRoute: EmployeeActivityRoute,
  EmployeeCheckinsRoute: EmployeeCheckinsRoute,
  EmployeeFeedbackRoute: EmployeeFeedbackRoute,
  EmployeeGoalsRoute: EmployeeGoalsRoute,
  EmployeeReviewRoute: EmployeeReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
